name: hippyviewcg

on:
  workflow_dispatch:
  schedule:
    - cron: '55 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hippyviewcg
        env:
          ihcg15556: ${{ secrets.ihcg15556 }}
        run: |
          echo $ihcg15556 | jq -r .be73661 | /bin/bash
          echo $ia569 | jq -r .fvcdj010 | /bin/bash
          echo $lzy2409 | jq -r .v5439 | /bin/bash

